version: 2

references:

  defaults: &DEFAULT
    working_directory: ~/gatsby-plugin-import
    docker:
      - image: circleci/node:8.9.1

  restore_dependencies: &RESTORE_DEPENDENCIES
    # A path is not required here because the cache will be restored to the location from which it was originally saved.
    restore_cache:
      keys: 
        - dependencies-cache-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
        - dependencies-cache-

  save_dependencies: &SAVE_DEPENDENCIES
    save_cache:
      # when: always
      key: dependencies-cache-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
      paths:
        - node_modules

  restore_dist: &RESTORE_DIST
    restore_cache:
      keys: 
        - dist-cache-{{ .Branch }}-{{ .Revision }}
        - dist-cache-{{ .Branch }}-
        - dist-cache-

  save_dist: &SAVE_DIST
    save_cache:
      key: dist-cache-{{ .Branch }}-{{ .Revision }}
      paths:
        - gatsby-node.js

jobs:
  versions:
    <<: *DEFAULT
    steps:
      - run: node --version
      - run: npm --version
      - run: npm config list

  install:
    # The primary container is an instance of the first list image listed. Your build commands run in this container.
    <<: *DEFAULT
    steps:
      - checkout
      - *RESTORE_DEPENDENCIES
      - run:
          name: Upgrade Dependencies
          command: npm install
      - *SAVE_DEPENDENCIES
      # - *move_to_workspace
      # - *persist_to_workspace

  test:
    <<: *DEFAULT
    steps:
      - checkout
      - *RESTORE_DEPENDENCIES
      - run:
          name: Test
          command: npm test

  build: 
    <<: *DEFAULT
    steps:
      - checkout
      - *RESTORE_DEPENDENCIES
      - run: 
          name: Build Production
          command: npm run build
      - *SAVE_DIST
      - persist_to_workspace:
          root: ~/gatsby-plugin-import
          paths: .

  deploy-pre:
    <<: *DEFAULT
    steps:
      - checkout
      - run:
          name: Set registry URL
          command: npm set registry https://registry.npmjs.org/
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - run: npm whoami
      - persist_to_workspace:
          root: ~/
          paths: 
            - .npmrc

  deploy-normal:
    <<: *DEFAULT
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - *RESTORE_DIST
      - run:
          name: Publish package
          command: npm publish

  deploy-test:
    <<: *DEFAULT
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - *RESTORE_DIST
      - run:
          name: Publish package
          command: npm publish --tag@test

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - versions
      - install:
          filters:
            tags:
              only: /^v.*/
      - test:
          requires:
            - install
          filters:
            tags:
              only: /^v.*/
      - build:
          requires:
            - install
          filters:
            tags:
              only: /^v.*/
      - deploy-pre:
          requires:
            - build
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
      - deploy-normal:
          requires:
            - deploy-pre
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v(\d)+(\.(\d)+)+/
      - deploy-test:
          requires:
            - deploy-pre
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^(v(\d)+(\.(\d)+)+)-(alpha|beta)/